version: '3.8'

services:
  web-scraper:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3